query Messages($conversationId: ID!) {
  messages(conversationId: $conversationId) {
    id
    content
    insertedAt
    user {
      email
    }
  }

  attachments(conversationId: $conversationId) {
    id
    url
    insertedAt
    user {
      id
      email
    }
  }
}
