version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  db-admin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@chat.app
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - db-admin:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

volumes:
  database:
    name: chat-database
  db-admin:
    name: pgadmin-database
