# https://taskfile.dev

version: "3"

tasks:
  default:
    - task: help

  routes:
    - mix phx.routes -r Chat.Router

  reset:
    cmds:
      - task: clean
      - task: setup

  clean:
    cmds:
      - mix clean
      - mix ecto.drop
      - rm -rf ./assets/node_modules
      - rm -rf ./uploads

  migrate:
    cmds:
      - mix ecto.migrate

  server:
    deps: [migrate]
    cmds:
      - mix phx.server
  iex.server:
    deps: [migrate]
    cmds:
      - iex -S mix phx.server
  iex:
    deps: [migrate]
    cmds:
      - iex -S mix
  setup:
    cmds:
      - mix deps.get
      - mix compile
      - mix ecto.setup
      - npm install --prefix assets

    status:
      - test -d ./assets/node_modules
      - test -d ./_build

  seed:
    - mix run priv/repo/seeds.exs

  react.devtools:
    - npx --prefix assets react-devtools
  backend.test:
    cmds:
      - mix test

  backend.test.wip:
    cmds:
      - mix test --only wip

  frontend.test:
    dir: ./assets
    cmds:
      - elm-test

  frontend.test.watch:
    dir: ./assets
    cmds:
      - elm-test --watch
  help:
    - echo "This is the cli tool for managing the rpoject"
