# https://taskfile.dev

version: "3"

tasks:
  default:
    - task: help

  routes:
    - mix phx.routes -r Chat.Router

  reset:
    cmds:
      - task: clean
      - task: setup

  clean:
    cmds:
      - mix clean
      - mix ecto.drop
      - rm -rf ./assets/node_modules
      - rm -rf ./uploads

  migrate:
    cmds:
      - mix ecto.migrate

  server:
    deps: [migrate]
    cmds:
      - mix phx.server
  iex.server:
    deps: [migrate]
    cmds:
      - iex -S mix phx.server
  iex:
    deps: [migrate]
    cmds:
      - iex -S mix

  setup.frontend:
    dir: ./assets
    cmds:
      - npm install

  setup:
    cmds:
      - task: setup.frontend
      - mix deps.get
      - mix compile
      - mix ecto.setup

    status:
      - test -d ./assets/node_modules
      - test -d ./_build

  seed:
    - mix run priv/repo/seeds.exs

  react.devtools:
    dir: ./assets
    cmds:
      - npx react-devtools

  test.backend:
    cmds:
      - mix test

  test.backend.wip:
    cmds:
      - mix test --only wip

  test.frontend:
    dir: ./assets
    cmds:
      - npm run test

  test.frontend.watch:
    dir: ./assets
    cmds:
      - npm run test.watch

  help:
    - echo "This is the cli tool for managing the project"
