name: Test
on: push
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: "3.x"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
          restore-keys: ${{runner.os}}-npm-
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{runner.os}}-elixir-${{hashFiles('**/mix.lock')}}
          restore-keys: ${{runner.os}}-mix-
      - uses: actions/setup-elixir@v1
        with:
          otp-version: "23.2"
          elixir-version: "1.10.4"
      - name: Setup
        run: task ci.setup
      - name: Run tests
        run: task ci.test.frontend
  backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: "3.x"
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: "23.2"
          elixir-version: "1.10.4"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
          restore-keys: ${{runner.os}}-npm-
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{runner.os}}-elixir-${{hashFiles('**/mix.lock')}}
          restore-keys: ${{runner.os}}-elixir-
      - name: Setup
        run: task ci.setup
      - name: Run tests
        run: task ci.test.backend
