name: Test
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: "3.x"
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
          restore-keys: ${{runner.os}}-npm-
      - name: Restore deps cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}z-${{ hashFiles('**/mix.lock') }}

      - uses: actions/setup-elixir@v1
        with:
          otp-version: "23.2"
          elixir-version: "1.10.4"
      - name: Setup
        run: task ci.setup
      - name: Run tests
        run: task ci.test.frontend
  backend:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: "3.x"
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: "23.2"
          elixir-version: "1.10.4"
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
          restore-keys: ${{runner.os}}-npm-
      - name: Restore deps cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{runner.os}}-mix-
      - name: Restore _build cache
        uses: actions/cache@v2
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{runner.os}}-build-
      - name: Restore plt cache
        uses: actions/cache@v2
        with:
          path: priv/plts
          key: ${{ runner.os }}-plt-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-plt-
      - name: Setup
        run: task ci.setup

      - name: Checking Formatting
        run: task ci.format

      - name: Running Dialyzer
        run: task ci.dialyzer

      - name: Run tests
        run: task ci.test.backend
